package com.asktech.pgateway.enums;

public enum FormValidationExceptionEnums {
	FATAL_EXCEPTION, 
	ALL_FIELDS_MANDATORY, 
	FIELED_NOT_FOUND, 
	UNICONTRAINT_VIOLATION, 
	SQLERROR_EXCEPTION,
	SIGNATURE_VERIFICATION_ERROR, 
	SIGNATURE_VERIFICATION_FAILED , 
	JSON_PARSE_EXCEPTION,	
	MERCHANT_ALREADY_EXISTS,
	MERCHANT_NOT_FOUND,
	PG_SERVICE_NOT_MAPPED_WITH_MERCHANT,
	EMAIL_ID_NOT_FOUND,
	USER_STATUS_BLOCKED,
	USER_STATUS_REMOVED,
	PASSWORD_VALIDATION_ERROR,
	INITIAL_PASSWORD_CHANGE_REQUIRED,
	SESSION_NOT_FOUND,
	JWT_EXPIRED, 
	JWT_MISSING, 
	JWT_SIGNATURE_MISSING, 
	JWT_FORMATE_INVALID, 
	JWT_UNSUPPORTED, 
	SESSION_EXPIRED, 
	IDEAL_SESSION_EXPIRED, 
	JWT_NOT_VALID, 
	USER_NOT_FOUND,
	REST_TEMPLATE_NOT_CALL, 
	JWT_ILLEGAL_ARGUMENT, 
	SESSION_DEAD,
	MERCHANT_BANK_DETAILS_EXISTS,
	MERCHANT_PG_APP_ID_NOT_FOUND,
	FORM_VALIDATION_FILED, MERCHANT_PG_SECRET_NOT_FOUND, MERCHANT_PG_NAME_NOT_FOUND, DUPLICATE_COMMISSON_FOR_MERCHANT, PG_VLIDATION_ERROR, 
	MERCHANT_BANK_DETILS_NOT_FOUND, DUPLICATE_ORDERID, INVALID_COOKIE_EXCEPTION, UNKNOWN_OPTION;

	FormValidationExceptionEnums() {

	}
}
